apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-devops-python-hpa
  namespace: app-test
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-devops-python-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
