name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker build -t trucco10/demo-devops-python:${{ github.run_number }} .

    - name: Push Docker image to Docker Hub
      run: docker push trucco10/demo-devops-python:${{ github.run_number }}

    - name: Update Kubernetes deployment
       uses: azure/k8s-set-context@v1
       with:
         kubeconfig: ${{ secrets.KUBE_CONFIG }}
       run: |
         cd kubernetes
         kubectl set image deployment/demo-devops-python-deployment demo-devops-python-container=trucco10/demo-devops-python:${{ github.run_number }} -n demo-deployment
