name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Docker CLI
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        gcloud auth configure-docker

    - name: Export Kubeconfig
      run: echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml

    - name: Set up Kubectl
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Build Docker image
      run: docker build -t trucco10/demo-devops-python:${{ github.run_number }} .

    - name: Push Docker image to Container Registry
      run: docker push trucco10/demo-devops-python:${{ github.run_number }}

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/demo-devops-python-deployment demo-devops-python-container=trucco10/demo-devops-python:${{ github.run_number }} -n demo-deployment
