name: CI/CD

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Docker image name
      run: |
        DOCKER_IMAGE_FULLNAME="$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME"
        echo "Docker image name: $DOCKER_IMAGE_FULLNAME"
    
    - name: Push Docker image
      run: |
        DOCKER_IMAGE_FULLNAME="$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME"
        docker build -t $DOCKER_IMAGE_FULLNAME .
        docker push $DOCKER_IMAGE_FULLNAME



    - name: Configure Kubectl for Minikube
      run: |
        minikube -p minikube kubectl config view --raw > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/demo-devops-python-deployment demo-devops-python-container=${{ secrets.DOCKERHUB_USERNAME }}/demo-devops-python:${{ github.run_number }} -n demo-deployment
