name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install flake8


    - name: Run Unit Tests
      run: |
        python manage.py test

    - name: Code Coverage
      run: |
        coverage run manage.py test
        coverage report -m


    - name: Static Code Analysis 
      run: |
        flake8 demo
    
    - name: Trigger CD if tests pass
      if: ${{ steps.unit-tests.outcome == 'success' }}
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true